//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANSWERS()
        {
            this.TESTING = new HashSet<TESTING>();
        }
    
        public int ID_ANSWER { get; set; }
        public string ANSWER { get; set; }
        public Nullable<short> TRUE_ANSWER { get; set; }
        public Nullable<int> ID_QUESTION { get; set; }
    
        public virtual QUESTIONS QUESTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTING> TESTING { get; set; }
    }
}
