//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class is4_KrasnikovaA_BaseTestingEntities : DbContext
    {
        public is4_KrasnikovaA_BaseTestingEntities()
            : base("name=is4_KrasnikovaA_BaseTestingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANSWERS> ANSWERS { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<QUESTIONS> QUESTIONS { get; set; }
        public virtual DbSet<REGISTRATION> REGISTRATION { get; set; }
        public virtual DbSet<STUDENTS> STUDENTS { get; set; }
        public virtual DbSet<SUBJECTS> SUBJECTS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TEACHERS> TEACHERS { get; set; }
        public virtual DbSet<TEST_T> TEST_T { get; set; }
        public virtual DbSet<TESTING> TESTING { get; set; }
        public virtual DbSet<THEME_T> THEME_T { get; set; }
    }
}
