//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRATION()
        {
            this.TESTING = new HashSet<TESTING>();
        }
    
        public int ID_REGISTRATION { get; set; }
        public Nullable<System.TimeSpan> START_TIME { get; set; }
        public Nullable<System.TimeSpan> END_TIME { get; set; }
        public Nullable<System.DateTime> THE_DATE_OF_THE { get; set; }
        public Nullable<int> ID_STUDENT { get; set; }
    
        public virtual STUDENTS STUDENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTING> TESTING { get; set; }
    }
}
