//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENTS()
        {
            this.REGISTRATION = new HashSet<REGISTRATION>();
        }
    
        public int ID_STUDENT { get; set; }
        public string SURNAME_STUDENT { get; set; }
        public string NAME_STUDENT { get; set; }
        public string PATRONYMIC_STUDENT { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORDD { get; set; }
        public Nullable<int> ID_GROUP { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRATION> REGISTRATION { get; set; }
    }
}
