//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHERS()
        {
            this.SUBJECTS = new HashSet<SUBJECTS>();
        }
    
        public int ID_TEACHER { get; set; }
        public string SURNAME_TEACHER { get; set; }
        public string NAME_TEACHER { get; set; }
        public string PATRONYMIC_TEACHER { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORDD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECTS> SUBJECTS { get; set; }
    }
}
