//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWPFClientEx.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Copies()
        {
            this.Readings = new HashSet<Readings>();
        }
    
        public int IdCopy { get; set; }
        public Nullable<int> IdBook { get; set; }
        public string InvNum { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public Nullable<System.DateTime> DecommissionDate { get; set; }
    
        public virtual Books Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Readings> Readings { get; set; }
    }
}
